[project]
name = "test-dev-versions"
version = "0.1.0"
description = "Test project for dev version parsing"

dependencies = [
    "requests>=2.28.0",
    "django>=4.2.0",
    "fastapi>=0.100.0",
    "test-package>=25.1",
    "dev-package>=18.0.1.dev0",
    "alpha-package>=1.2.3a1",
    "beta-package>=2.0.0b2",
    "rc-package>=3.1.0rc1",
    "post-package>=1.0.0.post1",
    "complex-dev>=18.0.1.dev0+g1234567"
]

[dependency-groups]
dev = [
    "pytest>=7.0.0",
    "coverage>=25.1",
    "dev-tool>=18.0.1.dev0"
] 